services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net

  remote_host:
    container_name: remote-host
    image: remote-host:v1
    build:
      context: rocky9
    networks:
      - net

  db_host:
    container_name: db
    image: mysql:5.7.43
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net

networks:
  net: