trigger:
- main

pool:
    vmImage: 'ubuntu-latest'


variables:
  IMAGE_REGISTRY_CONNECTON: 'ACR Demo'
  IMAGE_REGISTRY: 'ADODemo'
  IMAGE_REPOSITORY: 'adodemo.azurecr.io'
  TAG: '$(Build.BuildId)' 	


stages:

- stage: BuildApp
  jobs:
  - job: BuildPushImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(IMAGE_REGISTRY_CONNECTON)'
        repository: '$(IMAGE_REPOSITORY)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(TAG)'



- stage: DeployDev
  jobs:
  - job: DeployDev
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure'
        appType: 'webAppContainer'
        WebAppName: 'ADODemo-dev'
        DockerNamespace: '$(IMAGE_REGISTRY)'
        DockerRepository: '$(IMAGE_REPOSITORY)'
        DockerImageTag: '$(TAG)'

- stage: DeployTest
  jobs:
  - job: DeployTest
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure'
        appType: 'webAppContainer'
        WebAppName: 'ADODemo-test'
        DockerNamespace: '$(IMAGE_REGISTRY)'
        DockerRepository: '$(IMAGE_REPOSITORY)'
        DockerImageTag: '$(TAG)'
