apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: YWRtaW4K
  password: c3VwZXJzZWNyZXQK

# Esto se puede crear a mano:
# Kubectl create secret generic db-credentials-v2 --from-litaral=username=admin --from-literal password=supersecret