apiVersion: v1
kind: Service
metadata:
  name: python-demo-service
  labels:
    app: python-demo-service
spec:
  selector:
    app: python-demo-deployment
  ports:
    - port: 8080
  type: ClusterIP
